### ISSUE TITLE
Create a Global Unit

### ISSUE THREAD

**Issue by arch-usr** [Mulder-Oosthuizen-10100/sikuli-selenium-testing#1]
This unit will be used for the FindElement function and the other similar functions.

**Comment by Mulder-Oosthuizen** [comment]
Issue Resolved with commit [df66d99](https://github.com/Mulder-Oosthuizen-10100/sikuli-selenium-testing/commit/df66d9914d0b4f9a9cfda908a93e24b62be70e20)

**Comment by Mulder-Oosthuizen** [comment]
Issue Resolved with commit [df66d99](https://github.com/Mulder-Oosthuizen-10100/sikuli-selenium-testing/commit/df66d9914d0b4f9a9cfda908a93e24b62be70e20)
