### ISSUE TITLE
Add Reporting Module

### ISSUE THREAD

**Issue by arch-usr** [Mulder-Oosthuizen-10100/sikuli-selenium-testing#2]
The reporting module will be used to report on the successfulness of the test cases.

**Comment by Mulder-Oosthuizen** [comment]
Issue Resolved with commit [cca0b74](https://github.com/Mulder-Oosthuizen-10100/sikuli-selenium-testing/commit/cca0b74da0dc073d5d128b53b4d4eb0963846040)
