### ISSUE TITLE
Make image path Relative

### ISSUE THREAD

**Issue by arch-usr** [Mulder-Oosthuizen-10100/sikuli-selenium-testing#3]
If a collaborator would like to work on the project, the image folder location paths should be relative to the project root.

**Comment by Mulder-Oosthuizen** [comment]
Issue Resolved with commit [df66d99](https://github.com/Mulder-Oosthuizen-10100/sikuli-selenium-testing/commit/df66d9914d0b4f9a9cfda908a93e24b62be70e20)
